### ISSUE TITLE
Build fails on Arch

### ISSUE THREAD

**Issue by mtompkins** [verticalcoin/verticalcoin#3]
Same problem documented here:
https://github.com/zcoinofficial/zcoin/issues/193

**Comment by DerUntote** [comment]
can you please try to compile V1.3 branch? 

we have several build setups. 
https://travis-ci.org/verticalcoin/verticalcoin/builds/390430263

you compile, like it is under Ubuntu?

./autogen.sh
./configure
make

**Comment by mtompkins** [comment]
Thank you for your reply. Compilation "like under Ubuntu" doesn't work for different distros.
You would need to address your code in a manner consistent with the reference I provided to address the failure.
